module.exports = {
  trainingTypes: {
    1: "AMI",
    2: "AMS",
    3: "MCI",
    4: "SNM",
    5: "Other"
  },
  locationTypes: {
    1: "Urban",
    2: "Suburban",
    3: "Small City",
    4: "Rural"
  },
  orgStructures: {
    1: "Public District",
    2: "Public Magnet",
    3: "Public Charter",
    4: "Public Innovation",
    5: "Private For Profit Single Owner",
    6: "Private For Profit Corporate Owner",
    7: "Private Non-Profit"
  },
  sizes: {
    1: "Small",
    2: "Medium",
    3: "Large",
    4: "Extra Large"
  },
  cals: {
    1: "Traditional",
    2: "Year-Round"
  },
  states: {
    1: "Alabama",
    2: "Alaska",
    3: "Arizona",
    4: "Arkansas",
    5: "California",
    6: "Colorado",
    7: "Connecticut",
    8: "Delaware",
    9: "Florida",
    10: "Georgia",
    11: "Hawaii",
    12: "Idaho",
    13: "Illinois",
    14: "Indiana",
    15: "Iowa",
    16: "Kansas",
    17: "Kentucky",
    18: "Lousiana",
    19: "Maine",
    20: "Maryland",
    21: "Massachusetts",
    22: "Michigan",
    23: "Minnesota",
    24: "Mississippi",
    25: "Missouri",
    26: "Montana",
    27: "Nebraska",
    28: "Nevada",
    29: "New Hampshire",
    30: "New Jersey",
    31: "New Mexico",
    32: "New York",
    33: "North Carolina",
    34: "North Dakota",
    35: "Ohio",
    36: "Oklahoma",
    37: "Oregon",
    38: "Pennsylvania",
    39: "Rhode Island",
    40: "South Carolina",
    41: "South Dakota",
    42: "Tennessee",
    43: "Texas",
    44: "Utah",
    45: "Vermont",
    46: "Virginia",
    47: "Washington",
    48: "West Virginia",
    49: "Wisconsin",
    50: "Wyoming"
  },
  traits: {
    1: "ambitious",
    2: "humorous",
    3: "collaborative",
    4: "independent",
    5: "extroverted",
    6: "introverted",
    7: "artistic",
    8: "musical",
    9: "creative",
    10: "organized",
    11: "playful",
    12: "quiet",
    13: "verbal communicator",
    14: "written communicator",
    15: "joyful",
    16: "tech oriented",
    17: "analog",
    18: "patient",
    19: "spontaneous",
    20: "routine oriented"
  },
  ageRanges: {
    1: "0-3",
    2: "3-6",
    3: "6-9",
    4: "9-12",
    5: "12-14",
    6: "15-18"
  }
};

{
      0: "AK",
      1: "AL",
      2: "AR",
      3: "AZ",
      4: "CA",
      5: "CO",
      6: "CT",
      7: "DC",
      8: "DE",
      9: "FL",
      10: "GA",
      11: "HI",
      12: "IA",
      13: "ID",
      14: "IL",
      15: "IN",
      16: "KS",
      17: "KY",
      18: "LA",
      19: "MA",
      20: "MD",
      21: "ME",
      22: "MI",
      23: "MN",
      24: "MO",
      25: "MS",
      26: "MT",
      27: "NC",
      28: "ND",
      29: "NE",
      30: "NH",
      31: "NJ",
      32: "NM",
      33: "NV",
      34: "NY",
      35: "OH",
      36: "OK",
      37: "OR",
      38: "PA",
      39: "RI",
      40: "SC",
      41: "SD",
      42: "TN",
      43: "TX",
      44: "UT",
      45: "VA",
      46: "VT",
      47: "WA",
      48: "WI",
      49: "WY"
