const actionTypes = {
  GET_CURRENT_USER_REQUESTED: "GET_USER_REQUESTED",
  GET_CURRENT_USER_REJECTED: "GET_CURRENT_USER_REJECTED",
  GET_CURRENT_USER_FULFILLED: "GET_CURRENT_USER_FULFILLED",
  GET_CURRENT_USER_PROFILE: "GET_USER_PROFILE",
  GET_CURRENT_USER_MATCHING_PROFILE: "GET_MATCHING_PROFILE"
};

export default actionTypes;
